# Generated by Django 3.0.3 on 2020-07-20 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question',
            field=models.TextField(default='abc'),
            preserve_default=False,
        ),
    ]
