# Generated by Django 3.0.3 on 2020-07-24 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_question_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='viewed',
            field=models.BooleanField(default=False),
        ),
    ]
