# Generated by Django 3.0.3 on 2020-07-26 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0007_class_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='classes',
            field=models.ManyToManyField(to='quiz.Class'),
        ),
    ]
