# Generated by Django 3.0.3 on 2020-07-26 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0008_quiz_classes'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='make_visible',
            field=models.BooleanField(default=False),
        ),
    ]
