# Generated by Django 3.0.3 on 2020-07-27 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0009_quiz_make_visible'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentquizinfo',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
