# Generated by Django 3.0.3 on 2020-07-27 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0010_studentquizinfo_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='total_questions',
            field=models.IntegerField(default=0),
        ),
    ]
