# Generated by Django 3.0.3 on 2020-07-28 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0012_question_multiple_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='figure',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
