# Generated by Django 3.0.3 on 2020-07-28 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0014_auto_20200728_1124'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='year',
            field=models.IntegerField(default=3),
            preserve_default=False,
        ),
    ]
