# Generated by Django 3.0.3 on 2020-07-28 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0015_class_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='branch',
            field=models.CharField(default='Computers', max_length=50),
            preserve_default=False,
        ),
    ]
