# Generated by Django 3.0.3 on 2020-07-28 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0017_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='answer_available',
            field=models.BooleanField(default=False),
        ),
    ]
