# Generated by Django 3.0.3 on 2020-07-29 13:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0021_quiz_timer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='timer',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(20), django.core.validators.MaxValueValidator(40)]),
        ),
    ]
