# Generated by Django 3.0.3 on 2020-07-30 10:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0022_auto_20200729_1331'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='spam',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='timer',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(9), django.core.validators.MaxValueValidator(31)]),
        ),
    ]
