# Generated by Django 3.0.3 on 2020-07-31 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0025_auto_20200731_1712'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poll',
            name='deactivate',
        ),
    ]
