# Generated by Django 3.0.3 on 2020-08-02 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0028_remove_poll_show_result'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poll',
            name='description',
        ),
    ]
