# Generated by Django 3.0.3 on 2020-08-06 12:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0029_remove_poll_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='timer',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(9), django.core.validators.MaxValueValidator(120)]),
        ),
    ]
